In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('CSV_files/Final_Business_Data.csv')

In [3]:
df.head()

,Restaurant_ID,Restaurants_Name,Address,City,State,Postal_Code,Latitude,Longitude,Stars_Rating,Review_Count,...,Alcohol,Good_For_Kids,Reservations,Restaurants_TakeOut,WiFi,Good_For_Groups,Wheelchair_Accessible,Happy_Hour,Noise_Level,Dietary_Restrictions
0,MTSW4McQd7CbVtyjqoe9mw,St Honore Pastries,935 Race St,Philadelphia,PA,19107.0,39.955505,-75.155564,4.0,80,...,1,0,0,1,1,0,0,0,1,0
1,0bPLkL0QhhPO5kt1_EXmNQ,Zio's Italian Market,2575 E Bay Dr,Largo,FL,33771.0,27.916116,-82.760461,4.5,100,...,1,1,0,1,0,0,1,0,4,0
2,MUTTqe8uqyMdBl186RmNeA,Tuna Bar,205 Race St,Philadelphia,PA,19106.0,39.953949,-75.143226,4.0,245,...,1,0,1,1,1,1,1,1,4,0
3,ROeacJQwBeh05Rqg7F6TCg,BAP,1224 South St,Philadelphia,PA,19147.0,39.943223,-75.162568,4.5,205,...,1,1,0,1,0,0,0,0,1,0
4,9OG5YkX1g2GReZM0AskizA,Romano's Macaroni Grill,5505 S Virginia St,Reno,NV,89502.0,39.476117,-119.789339,2.5,339,...,1,1,1,1,1,1,0,1,4,0

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27207 entries, 0 to 27206
Data columns (total 24 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Restaurant_ID          27207 non-null  object
 1   Restaurants_Name       27207 non-null  object
 2   Address                27136 non-null  object
 3   City                   27207 non-null  object
 4   State                  27207 non-null  object
 5   Postal_Code            27205 non-null  float64
 6   Latitude               27207 non-null  float64
 7   Longitude              27207 non-null  float64
 8   Stars_Rating           27207 non-null  float64
 9   Review_Count           27207 non-null  int64
 10  Restaurants_Delivery   27207 non-null  int64
 11  Outdoor_Seating        27207 non-null  int64
 12  Accepts_CreditCards    27207 non-null  int64
 13  Price_Range            27207 non-null  int64
 14  Alcohol                27207 non-null  int64
 15  Good_For_Kids          27207 non-null  int64
 16  Reservations           27207 non-null  int64
 17  Restaurants_TakeOut    27207 non-null  int64
 18  WiFi                   27207 non-null  int64
 19  Good_For_Groups        27207 non-null  int64
 20  Wheelchair_Accessible  27207 non-null  int64
 21  Happy_Hour             27207 non-null  int64
 22  Noise_Level            27207 non-null  int64
 23  Dietary_Restrictions   27207 non-null  int64
dtypes: float64(4), int64(15), object(5)
memory usage: 5.0+ MB

In [5]:
df['Postal_Code'] = df['Postal_Code'].fillna(0)
df['Postal_Code'] = df['Postal_Code'].astype("int64")
df.drop(df.loc[df['Postal_Code']==0].index, inplace=True)

In [6]:
df.dtypes

Restaurant_ID             object
Restaurants_Name          object
Address                   object
City                      object
State                     object
Postal_Code                int64
Latitude                 float64
Longitude                float64
Stars_Rating             float64
Review_Count               int64
Restaurants_Delivery       int64
Outdoor_Seating            int64
Accepts_CreditCards        int64
Price_Range                int64
Alcohol                    int64
Good_For_Kids              int64
Reservations               int64
Restaurants_TakeOut        int64
WiFi                       int64
Good_For_Groups            int64
Wheelchair_Accessible      int64
Happy_Hour                 int64
Noise_Level                int64
Dietary_Restrictions       int64
dtype: object

In [7]:
df.count()

Restaurant_ID            27205
Restaurants_Name         27205
Address                  27136
City                     27205
State                    27205
Postal_Code              27205
Latitude                 27205
Longitude                27205
Stars_Rating             27205
Review_Count             27205
Restaurants_Delivery     27205
Outdoor_Seating          27205
Accepts_CreditCards      27205
Price_Range              27205
Alcohol                  27205
Good_For_Kids            27205
Reservations             27205
Restaurants_TakeOut      27205
WiFi                     27205
Good_For_Groups          27205
Wheelchair_Accessible    27205
Happy_Hour               27205
Noise_Level              27205
Dietary_Restrictions     27205
dtype: int64

In [8]:
df.to_csv('CSV_files/Business.csv', index=False)